services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=takina
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  takina:
    image: ghcr.io/orangci/takina:latest
    restart: always
    environment:
      - TOKEN=${TOKEN} # You put your bot's token here
      - PREFIX=. # You can always change this to any prefix you want
      - HASDB=yes
      - MONGO=mongodb://takina:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?directConnection=true
      - BOT_NAME=Takina
      - DB_NAME=takina
      - EMBED_COLOR=0x2B2D31
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN} # if you want the github command in util.socials to work, set this variable
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID} # You must set this and the below environment variable if you want the reddit command in util.socials to work. To get your own Reddit client secret and ID visit https://www.reddit.com/prefs/apps.
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET} # see above

volumes:
  data-volume:
